name: qr_code
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  screenshot: ^3.0.0
  pretty_qr_code: ^3.3.0
  share_plus: ^10.1.2
    # untuk scan
  mobile_scanner: ^6.0.2
    # minta akses untuk buka kamera
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.14.2
  device_preview: ^1.2.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_gelScan.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Manrope
      fonts: 
        - asset: assets/fonts/Manrope-Regular.ttf
